# In order to build the docker image, you have to run the following commands:
# $ curl http://zeroday.biz/media/Dockerfile
# $ docker build .
#
# Then run this command to run the container:
# $ docker run --env PORT=8080 -it -p 8080:8080/tcp <container ID>

FROM node:10

WORKDIR /usr/src/app

RUN git clone https://api.glitch.com/git/crinolo-swgoh/ .

RUN npm install

RUN npm ci --only=production

EXPOSE 8080

CMD [ "node", "server.js" ]
