# How to setup this docker container:
# mkdir crinolo
# cd crinolo
# curl -O http://zeroday.biz/media/Dockerfile
# docker build .
# docker run --env PORT=8080 -it -p 8080:8080/tcp <container ID>

FROM node:10

WORKDIR /usr/src/app

RUN git clone https://api.glitch.com/git/crinolo-swgoh/ .

RUN npm install

RUN npm ci --only=production

EXPOSE 8080

CMD [ "node", "server.js" ]
