#!/bin/bash

grep --color --exclude='*.css' --exclude='*.js' --exclude='*.json' --exclude='*.pyc' --exclude='*.txt' --exclude='*.png' --exclude-dir='.git' --exclude-dir='ENV' --exclude-dir='logs' --exclude-dir='__pycache__' "${@}"
