#!/bin/bash

grep --color --exclude='*.css' --exclude='*.js' --exclude='*.json' --exclude='*.less' --exclude='*.map' --exclude='*.pyc' --exclude='*.txt' --exclude='*.scss' --exclude='*.sql' --exclude='*.svg' --exclude='*.png' --exclude='*.yml' --exclude-dir='.git' --exclude-dir='ENV' --exclude-dir='logs' --exclude-dir='__pycache__' --exclude-dir='protos' "${@}"
