# Generated by Django 2.2.1 on 2019-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swgoh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.IntegerField(unique=True),
        ),
    ]
